Add support for python 3.11
networkit/networkit pull request #1000
Opened 2022-10-25 14:45 UTC by Thijss

I've created a first draft for a python 3.11 support PR

closes #999

2022-10-27 09:14 UTC, fabratu requested changes
Thanks for the pull request!

There are some minor comments. Once they are fixed, I will enable to CI to test the workflow updates.

2022-10-27 09:14 UTC, fabratu commented on .github/workflows/build_wheels.yml
> +          CIBW_BUILD: ${{ github.ref == 'refs/heads/master' && 'cp39-* cp310-* cp311-*' || 'cp311-*' }}
In the current state, aarch64 builds take long to build due to qemu. Adding another build version would be too much - therefore better remove 3.9.

2022-10-27 09:14 UTC, fabratu commented on .github/workflows/build_wheels.yml
> +          python-version: '3.11'
No need to change this (since this is only the environment for calling cibuildwheel). Better keep a stable, fixed tooling.

2022-10-27 09:14 UTC, fabratu commented on .github/workflows/build_wheels.yml
> +          python-version: '3.11'
Same as above.

2022-10-27 09:14 UTC, fabratu commented on .github/workflows/build_wheels.yml
> +          python-version: '3.11.0'
Same as above.

2022-10-27 09:14 UTC, fabratu commented on .github/workflows/build_wheels.yml
> +          python-version: '3.11.0'
Same as above.

2022-10-27 09:14 UTC, fabratu commented on .github/workflows/build_wheels.yml
> +          python-version: '3.11.0'
Same as above.

2022-11-01 09:17 UTC, Thijss commented
I am not sure what is causing the pipelines to fail. @fabratu do you have an idea?

2022-11-01 09:19 UTC, fabratu commented
> I am not sure what is causing the pipelines to fail. @fabratu do you have an idea?

Will be fixed by #1001. Should be merged soon.

2022-11-01 11:47 UTC, fabratu commented
> > I am not sure what is causing the pipelines to fail. @fabratu do you have an idea?
> 
> Will be fixed by #1001. Should be merged soon.

#1001 is merged, after a rebase the PR should build successfully.

2022-11-02 08:01 UTC, fabratu commented
Seems that cibuildwheel is not yet ready for Python 3.11 under manylinux2014 `aarch64` (maybe the image is too old). Since there will be a change to the soonish on how we built arm-wheels anyways, I would suggest to revert these changes for `aarch64` for this PR.

2022-11-02 10:23 UTC, Thijss commented
seems all good now :)

2022-11-02 10:24 UTC, fabratu approved these changes
LGTM. Thanks again for the PR.

2022-11-09 08:18 UTC, merged