python tests: improved structure, and ordered functions lexicographically
networkit/networkit pull request #1057
Opened 2023-05-05 09:53 UTC by PetholzA

This PR moves test_algorithms.py functions into the fitting modules and renames / restructures some of them

2023-05-14 09:37 UTC, angriman commented
Thank you, python tests needed a better structure. To simplify reviewing this PR, could you please split it in multiple commits?

2023-05-15 07:52 UTC, fabratu commented
Hm, I think that is too much hassle. Over 90% of the commit is moving the tests from `test_algorithms.py` to the appropriate module files. The other ~10% are renaming tests, removing comments and introduce sorting. Since I discussed the process leading to this PR already with @PetholzA, I will also take care of the review. 

Also, reworking/adding tests will be out-of-scope of this PR (we will start working on that shortly).

2023-05-22 09:14 UTC, fabratu requested changes
In addition to the change requests - can you please give a proper commit message?

2023-05-22 09:14 UTC, fabratu commented on networkit/test/test_centrality.py
>  class Test_Centrality(unittest.TestCase):
Sry for the inconvinience - can you please rename the classes to UpperCamelCase?

2023-05-22 09:14 UTC, fabratu commented on networkit/test/test_centrality.py
> +	def testCentralityApproxBetweenness(self):
I think we can delete the module name from the function definition without loosing information. On the command line a single test execution looks like this: 

```
testCentralityCoreDecomposition (test_centrality.Test_Centrality.testCentralityCoreDecomposition) ... ok
```

2023-05-31 05:30 UTC, fabratu approved these changes

2023-05-31 05:30 UTC, merged