MatricesGTest.hpp & test_centrality_py: adds testing functions
networkit/networkit pull request #1062
Opened 2023-05-16 13:25 UTC by PetholzA

adds testMatrixToGraph() in cpp, and test_Matrices, test_eigenvectorValues in python.

this not the final commit! it is meant to to check if the coverage increases

2023-05-22 10:26 UTC, PetholzA commented
note that the python test cases failed, because the previous PR  #1059 hasnt been pulled yet, if i change my files according to #1059 locally it works just fine

2023-05-31 05:36 UTC, fabratu commented
@PetholzA Please rebase on top of master.

2023-05-31 12:14 UTC, angriman requested changes
Thanks for adding new tests. In addition to the comments I left, my concern is that this PR does too many things at once (adds tests for different modules). I recommend splitting this PR in 4 different PRs (or commits):
- Add C++ MatricesGTests
- Add Python matrices tests
- Add Python max clique tests
- Add Python community tests.

2023-05-31 12:14 UTC, angriman commented on networkit/cpp/algebraic/test/MatricesGTest.cpp
> +    ASSERT_EQ(G.numberOfEdges(),6594);
```suggestion
    EXPECT_EQ(G.numberOfEdges(), 6594);
```
See http://google.github.io/googletest/reference/assertions.html

2023-05-31 12:14 UTC, angriman commented on networkit/cpp/algebraic/test/MatricesGTest.cpp
> +   // testMatrixToGraph<DenseMatrix>();
Why is this commented out?

2023-05-31 12:14 UTC, angriman commented on networkit/cpp/algebraic/test/MatricesGTest.cpp
> +
Drop.

2023-05-31 12:14 UTC, angriman commented on networkit/cpp/algebraic/test/MatricesGTest.cpp
> +
Drop.

2023-05-31 12:14 UTC, angriman commented on networkit/cpp/algebraic/test/MatricesGTest.cpp
> +    Matrix mat = Matrix::adjacencyMatrix(graphReader.read("input/power.graph"));
```suggestion
    Matrix mat = Matrix::adjacencyMatrix(METISGraphReader{}.read("input/power.graph"));
```

2023-05-31 12:14 UTC, angriman commented on networkit/test/test_centrality.py
> -
Drop.

2023-06-02 12:44 UTC, closed without merging