Add DynAlgorithm bindings to python
networkit/networkit pull request #1067
Opened 2023-05-23 17:08 UTC by bernlu

This PR adds python bindings for the `DynAlgorithm` class in a new `dynalgorithm.pxd`/`dynalgorithm.pyx` file and updates all existing dynamic algorithms to use this base class.

The setup is a little weird because of Cython limitations. First, a figure of the new class hierarchy:
<todo>

Explanation:
- Cython (or Python in general) does not allow multiple inheritance of `cdef class`es (also called 'extension types'). Since we use multiple inheritance for dynamic algorithms in c++ (inherit from `Algorithm` and `DynAlgorithm`), we do need this functionality though. The workaround is to define a wrapper class (`DynAlgorithm`) in pure python which wraps the cdef class, which can be inherited from.
- Cython also requires that all classes in a hierarchy have a common base class. Since there is no such class in C++ (and adding one would probably decrease performance because of more vtables), we instead add a dummy base class just for Cython (`CythonParentClass`). We move the `_Algorithm` pointer to this class s.t. both the `Algorithm` and the `DynAlgorithm` subclass trees have access to that pointer.

In the `_CythonSubclassDynAlgorithm.update` and `updateBatch` methods, we have to use a `dynamic_cast` call to cast the `_Algorithm` pointer to a `_DynAlgorithm` pointer. Regarding performance, I would not expect users to call this often enough to matter, but I also did a quick test and the difference seems to be around 100ns for a single call of dynamic_cast in this context.

2023-05-24 07:56 UTC, fabratu commented
As additional information. Importing the necessary `cppclass _DynAlgorithm` and `class DynAlgorithm` now has to be split (as seen on the PR changes):

```
from .dynbase cimport _DynAlgorithm
from .dynbase cimport DynAlgorithm
...
```

We found no way, creating a workaround using only `cimport`.

2023-05-31 05:49 UTC, fabratu requested changes

2023-05-31 05:49 UTC, fabratu commented on networkit/dynbase.pyx
> +    Cython does not allow direct inheritance from two extension types (cdef classes).
Indentation for the the docstring looks of. Also move the closing `"""` to another line.

2023-05-31 05:49 UTC, fabratu commented on networkit/dynbase.pyx
> +        Returns
Indentation error.

2023-05-31 05:49 UTC, fabratu commented on networkit/dynbase.pyx
> +        Returns
As above.

2023-05-31 05:49 UTC, fabratu commented on networkit/base.pyx
> +	Cython cannot handle multiple inheritance without this single common base class."""
Move the closing `"""` to another line.

2023-06-01 09:38 UTC, fabratu approved these changes
LGTM.

2023-06-07 17:03 UTC, bernlu commented
Small change: in our `*.pyx` files where we define `cdef cppclass _MyAlgorithm` we should not re-declare `update` and `updateBatch` (it suffices to declare them once in `dynbase`).
This is how we handle `run` as well (most of the time).
It seems like Cython can deal these multi-declarations, even when sometimes functions are declared with `nogil` and sometimes without, but for consistency they should be declared only once in base/dynbase. 
Fixed with this new commit.

2023-06-08 07:17 UTC, fabratu commented
> Small change: in our `*.pyx` files where we define `cdef cppclass _MyAlgorithm` we should not re-declare `update` and `updateBatch` (it suffices to declare them once in `dynbase`). This is how we handle `run` as well (most of the time). It seems like Cython can deal these multi-declarations, even when sometimes functions are declared with `nogil` and sometimes without, but for consistency they should be declared only once in base/dynbase. Fixed with this new commit.

Right, missed that in the previous review. Only checked, that update/updateBatch from cdef class were gone.

2023-06-08 11:16 UTC, merged