python unit tests: adds new tests for graph related functions
networkit/networkit pull request #1071
Opened 2023-05-29 11:10 UTC by PetholzA

this commit is mainly aimed to increase testing coverage, it tests functions from dynamics.pyx and mostly graph.pyx

2023-05-31 05:52 UTC, fabratu commented
@PetholzA Please rebase on top of master. So far, the PR has increased the coverage from 60% -> 66% for the graph module. If possible, it would be good to increase the coverage even more. Maybe that is done after the rebase though.

2023-06-04 10:08 UTC, angriman requested changes

2023-06-04 10:08 UTC, angriman commented on networkit/test/test_graph.py
> +		self.assertFalse(up1.__ge__(up2))
Using `__eq__`, `__ne__`, etc. should not be necessary, they enable using `==`, `<=`, etc. Please use `assertEqual`, `assertLessEqual`, etc.

2023-06-04 10:08 UTC, angriman commented on networkit/test/test_graph.py
> +		self.assertFalse(up1.__ge__(up2))
Also, these tests are not related with the GraphEventStream. Please move them to another test.

2023-06-04 10:08 UTC, angriman commented on networkit/test/test_graph.py
> +		self.assertEqual(G.numberOfNodes(), 4)
Please also test that the edges are as expected.

2023-06-04 10:08 UTC, angriman commented on networkit/test/test_graph.py
> +		self.assertEqual(G.numberOfNodes(), 2)
```suggestion
		self.assertEqual(G.numberOfNodes(), 2)
		setf.assertTrue(G.hasNode(1))
```

2023-06-04 10:08 UTC, angriman commented on networkit/test/test_graph.py
> +	def testEdgeWeight(self):
The name is too generic, and you are testing different behaviors here. Please split this test in more minimal and targeted tests. For example, one test to test `increaseWeight`, another one to test `swapEdge`, another one for `totalEdgeWeight`, etc.

2023-06-04 10:08 UTC, angriman commented on networkit/test/test_graph.py
> +		self.assertEqual(getInNeighborsWeight(0), 0.0)
Here you can use `weightedDegree` and `weightedDegreeIn`.

2023-06-05 19:18 UTC, angriman commented on networkit/test/test_graph.py
> +		self.assertIsInstance(up1.__repr__(),str)
I think that this is supposed to be used with `repr(up1)`. Also, we should test that the string representation works as intended, see the [implementation](https://github.com/networkit/networkit/blob/master/networkit/cpp/dynamics/GraphEvent.cpp#L17).

2023-06-14 21:00 UTC, angriman reviewed
Thank you, I left a few comments. I see that there are lots of unrelated changes (moving around existing code, adding/removing empty lines or white spaces). This makes reviewing PRs harder than necessary. If that's not too difficult, could you please drop these changes and only include the actual changes that you made?

2023-06-14 21:00 UTC, angriman commented on networkit/test/test_graph.py
> +
Drop the additional white spaces.

2023-06-14 21:00 UTC, angriman commented on networkit/test/test_graph.py
> +		#testing if the weight remained
```suggestion
		# Test that the total edge weight remained the same.
```

2023-06-14 21:00 UTC, angriman commented on networkit/test/test_graph.py
> +			self.assertEqual(sorted(forEdgesNbrs), sorted(nodeInNbrs))
I guess that this change was added by mistake.

2023-06-14 21:00 UTC, angriman commented on networkit/test/test_graph.py
> +		G.forNodesInRandomOrder(lambda u: self.assertFalse(G.hasEdge(u, 0)))
I don't follow the logic of this test. Shouldn't we check that the node `u` exists and that the iterator goes over all nodes?

2023-06-23 10:54 UTC, fabratu commented
The coverage is still below 80%. However, the main block missing are the node attributes. I would suggest leaving these out of this PR. Otherwise the PR might get too long.

2023-06-26 12:16 UTC, PetholzA commented
@angriman, your requests should mostly be adressed. I still left some "redundant" tests, because the goal was, to increase python testing coverage as much as possible.

2023-06-26 22:13 UTC, angriman reviewed
Thank you, just one minor thing. The rest LGTM.

2023-06-26 22:13 UTC, angriman commented on networkit/test/test_graph.py
> +		G.forNodesInRandomOrder(lambda u: self.assertIn(u, [0,1,2,3,4]))
```suggestion
		G.forNodesInRandomOrder(lambda u: self.assertTrue(G.hasNode(u)))
```

2023-06-27 21:21 UTC, angriman approved these changes

2023-07-05 09:34 UTC, merged