[WIP] python unit tests: adds more tests for flow, generators and engineering
networkit/networkit pull request #1072
Opened 2023-05-31 10:48 UTC by PetholzA

- test_flow should cover all existing functions
- generators is still in progress
- engineering is still in progress

2023-06-04 09:55 UTC, angriman commented
Thanks for adding more tests. Since this is still ongoing work, I converted it to draft.

2023-06-23 10:36 UTC, fabratu commented
ToDo Notes (based on an offline discussion):

- finish generators >=80%
- get engineering to 100% (basic functions, used everywhere)

2023-06-28 09:16 UTC, fabratu requested changes

2023-06-28 09:16 UTC, fabratu commented on networkit/test/test_generators.py
> +        g.fit(self.G)
Add asserts to test whether the new graph has the expected properties (e.g. `#nodes`, `#edges`).

2023-06-28 09:16 UTC, fabratu commented on networkit/test/test_generators.py
> +        g.fit(self.G)
Same as above (`fit` function).

2023-06-28 09:16 UTC, fabratu commented on networkit/test/test_generators.py
> +        g.fit(self.G)
Same as above (`fit` function).

2023-06-28 09:16 UTC, fabratu commented on networkit/test/test_generators.py
> +        g.fit(self.G)
Same as above (`fit` function).

2023-06-28 09:16 UTC, fabratu commented on networkit/test/test_generators.py
> +    """def testEdgeSwitchingMarkovChainGeneratorFit(self):
Is this intended?

2023-06-28 09:16 UTC, fabratu commented on networkit/test/test_generators.py
> +        g.fit(self.G)
Same as above (`fit` function).

2023-06-28 09:16 UTC, fabratu commented on networkit/test/test_generators.py
> +        g.fit(self.G)
Same as above (`fit` function).

2023-06-28 09:16 UTC, fabratu commented on networkit/test/test_generators.py
> +        g.fit(self.G)
Same as above (`fit` function).

2023-06-28 09:16 UTC, fabratu commented on networkit/test/test_generators.py
> +        g2.fit(self.G, vanilla=True, plfit=False)
Same as above (`fit` function). Also, better split the fit-test for `LFRGenerator` if different parameters use different lines of code.

2023-06-28 09:16 UTC, fabratu commented on networkit/test/test_generators.py
> +        g.fit(inputGraph, kronfit=False)
Same as above (`fit` function).

2023-07-12 11:24 UTC, fabratu commented on networkit/test/test_generators.py
> +        #print(g.generate().numberOfNodes())
Remove unnecessary lines.

2023-07-27 09:55 UTC, fabratu approved these changes

2023-08-04 11:48 UTC, merged