Unit testing: adds test_algebraic.py and more tests for MatricesGtest.cpp
networkit/networkit pull request #1074
Opened 2023-06-02 11:12 UTC by PetholzA

this PR splits up #1062 into semantically linked parts

2023-06-03 10:07 UTC, angriman requested changes
Thank you very much for the new tests. I left some comments.

2023-06-03 10:07 UTC, angriman commented on networkit/test/test_algebraic.py
> +	def testEigenvectorValues(self):
Here you are just testing that the first eigenvector type is complex. Shouldn't you check that the function produces the expected eigenvectors?

2023-06-03 10:07 UTC, angriman commented on networkit/cpp/algebraic/test/MatricesGTest.cpp
> +}
There is a more elegant way to instantiate a type-parametrized test suites: http://google.github.io/googletest/reference/testing.html#TYPED_TEST_SUITE_P

Anyway, this is not something introduced by this PR. This is ok for now, but we should change it later.

2023-06-03 10:07 UTC, angriman commented on networkit/cpp/algebraic/test/MatricesGTest.cpp
> +    EXPECT_EQ(G.numberOfEdges(), 6594);
What about testing also the number of nodes and that the produced edges are correct? Further, which kind of graph do we expect? Should be weighted/unweighted, directed/undirected? I think these properties should be tested.

2023-06-23 10:59 UTC, fabratu commented
Currently, the coverage is at 81%. Since the module is small, try to reach 100%.

2023-07-01 20:15 UTC, angriman approved these changes

2023-07-10 06:34 UTC, merged