[WIP] python tests: improves test_centrality
networkit/networkit pull request #1079
Opened 2023-06-07 12:10 UTC by PetholzA

this is not the final commit
also testKadabraBetweenness is commented out, because it currently results in seg fault

2023-06-10 12:17 UTC, angriman requested changes
Thank you for the tests, I left some comments.

I see that, while adding new tests, you followed what was already done for other algorithms (e.g., validating an approximation algorithm against itself or just checking the length of the scores list without testing the actual values). It is ok to replicate existing tests on other algorithms, I just don't think that the Python tests we have are appropriate.
In particular, I don't see the point of just checking that Python algorithms yield output of a given size/type. For example, instead of:
```
self.assertEqual(len(algo.ranking()), 4)
```
we should have
```
self.assertListEqual(algo.ranking(), [1,2,3,4])
```
While this might seem redundant because we already have C++ tests, it ensures that we haven't introduced bugs in the Cython layer. So my suggestion is to avoid replicating existing tests. New tests should:
- Check one behavior, do not test multiple functionalities of an algorithm in the same test.
- Validate the algorithm's output.

2023-06-12 10:22 UTC, PetholzA commented
@angriman Thank you very much for your comments, i try to include your suggestions from now on and retrospectivly. At multiple occasions it seemed very redundant to write a new testFunction for every single algorithm function, therefore i lumped them together, i can stop that according to your suggestions. Best regards

2023-06-23 11:13 UTC, fabratu commented
Coverage is at 84%, which is fine for `centrality`. I think we can finish this PR in order not to overload it. Removing the draft state.

2023-07-27 10:53 UTC, fabratu approved these changes

2023-08-04 11:48 UTC, merged