graph gtests: increases coverage
networkit/networkit pull request #1110
Opened 2023-08-09 09:39 UTC by PetholzA

this PR mainly adds tests for cases that had not been tested before

2023-08-25 14:17 UTC, fabratu requested changes

2023-08-25 14:17 UTC, fabratu commented on networkit/cpp/graph/Graph.cpp
> +        // if (degreeOut(u) != outEdges[u].size()) { //cannot evaluate to true
Based on an offline discussion: revert the changes and fix compactEdges() in another PR (so leave the function out of tests for now).

2023-08-25 14:17 UTC, fabratu commented on networkit/cpp/graph/Graph.cpp
> +            // if (directed && degreeIn(u) != inEdges[u].size()) { //cannot evalute to true
See above.

2023-08-25 14:17 UTC, fabratu commented on networkit/cpp/graph/test/GraphGTest.cpp
> +    G.addEdge(0, 1);
Better test with a small array of edgeId (so that it is clear, that the same ids still apply after the copy).

2023-08-25 14:17 UTC, fabratu commented on networkit/cpp/graph/test/GraphGTest.cpp
> +TEST(GraphGTest, testCompactEdgesAllVariations) {
See above (concerning `compactEdges()`).

2023-08-25 14:17 UTC, fabratu commented on networkit/cpp/graph/test/GraphToolsGTest.cpp
> +TEST_P(GraphToolsGTest, testParallelSumEdgesIndexed) {
TEST_P already tests for combinations of weighted/unweighted + directed/undirected. Better use this syntax (removes the duplicated code). Also, currently this test code should be launched four times (for all combinations of the parametrized test).

2023-08-27 11:08 UTC, angriman commented on networkit/cpp/graph/test/GraphGTest.cpp
> +    ASSERT_EQ(DW.numberOfEdges(), 4);
Here `EXPECT_EQ` would be more appropriate, https://testing.googleblog.com/2008/07/tott-expect-vs-assert.html

2023-08-27 11:08 UTC, angriman commented on networkit/cpp/graph/test/GraphToolsGTest.cpp
> +}
Same here.

2023-09-11 10:58 UTC, fabratu approved these changes

2023-09-21 08:02 UTC, merged