adds chungLuAlamEtAl generator + tests
networkit/networkit pull request #1177
Opened 2024-01-31 12:15 UTC by PetholzA

re-upload of #1166 from different fork

2024-02-26 06:12 UTC, fabratu commented
Since the code from this PR uses #1178, a review will be added once the corresponding feature is merged.

2024-06-10 11:29 UTC, fabratu requested changes

2024-06-14 07:18 UTC, PetholzA commented on networkit/cpp/generators/ChungLuGeneratorAlamEtAl.cpp
> +        maxGroupSize = 0xffffffffffffffffL;
The part concerning the lambda function has been addressed, while i am not sure what exactly you mean by switching between `parallel` and `!parallel` in the outer level (and it does not seem necessary).

2024-06-14 07:21 UTC, PetholzA commented on networkit/cpp/generators/ChungLuGeneratorAlamEtAl.cpp
> +        double randVal = real(rng);
While this is possible, as far as i can tell, Jannis used the preferred method described in https://networkit.github.io/dev-docs/cpp_api/function_namespaceAux_1_1Random_1ab0532015f7ed7d0eddffeb10405720f9.html for performance.

2024-06-26 08:01 UTC, fabratu requested changes

2024-06-26 13:07 UTC, PetholzA commented on networkit/cpp/generators/ChungLuGeneratorAlamEtAl.cpp
> +        maxGroupSize = 0xffffffffffffffffL;
i resolved this slightly differently by adding a additional `if clause` and documenting the behaviour

2024-07-05 11:11 UTC, fabratu requested changes

2024-07-05 11:11 UTC, fabratu commented on include/networkit/generators/ChungLuGeneratorAlamEtAl.hpp
> + * For reference of the concept of the original model see Chung, Lu: The average distances in random
`For reference, see the original model by Chung,...`

And use quotes to highlight the paper titles.

2024-07-05 11:11 UTC, fabratu commented on include/networkit/generators/ChungLuGeneratorAlamEtAl.hpp
> + * This implementation follows a newer parallelizable algorithm by M. Alam, M. Khan, A. Vullikanti
Concerning author naming: Name two authors + et al. afterwards.

2024-07-05 11:11 UTC, fabratu commented on include/networkit/generators/ChungLuGeneratorAlamEtAl.hpp
> + * Graphs". https://ieeexplore.ieee.org/document/7877110 . The time complexity is O(m/p + delta +
Use markdown style for URLS: 

```
["An Efficient and Scalable Algorithmic Method for Generating Large-Scale Random Graphs"](https://ieeexplore.ieee.org/document/7877110)
```

Best also add URLs to the other references.

2024-07-08 11:26 UTC, fabratu approved these changes

2024-07-11 08:54 UTC, merged