fix: LouvainMapGTest
networkit/networkit pull request #1185
Opened 2024-02-07 08:18 UTC by PetholzA

adresses #1184 to make the test deterministic: basically substituting the random clustering graph generator by non-random graph generator (BA)

2024-02-08 16:54 UTC, fabratu requested changes

2024-02-08 16:54 UTC, fabratu commented on networkit/cpp/community/test/LouvainMapEquationGTest.cpp
> +    BarabasiAlbertGenerator generator(50, n);
Better build three graphs with size `n/3` and merge them directly.

2024-04-07 08:14 UTC, angriman commented on networkit/cpp/community/test/LouvainMapEquationGTest.cpp
> +    }
Something like this is probably more readable:
```cpp
// Generates an std::unordered_set<node> with the sequence of consecutive integers in [start, end).
auto generateConsecutiveNodes = [](node start, node end) -> std::unordered_set<node> {
  std::vector<node> nodes(end - start);
  std::iota(nodes.begin(), nodes.end(), start);
  return {nodes.begin(), nodes.end()};
};
const Graph G1 = GraphTools::subgraphFromNodes(G, generateConsecutiveNodes(0, 100));
// ...
```

2024-05-02 11:40 UTC, fabratu approved these changes

2024-05-13 10:22 UTC, merged