Improve const correctness, documentation, and minor cleanup in graph module
networkit/networkit pull request #1274
Opened 2024-12-29 16:52 UTC by Schwarf

## Summary
This PR improves the graph module by addressing minor code and documentation issues. 

## Changes
1. **Move/Copy Constructors and Assignment Operators**:
   - Updated move and copy constructors, as well as assignment operators of `Graph` class, to handle a previously ignored member variable `deletedID`.

2. **Member Initialization**:
   - Fixed missing initialization for member variables of classes `NeighborRange` and `NeighborWeightRange`.

3. **Const Correctness**:
   - Updated member functions to ensure proper `const` correctness.
   
4. **Documentation**:
   - Fixed minor documentation issues, including typos and parameter names.

5. **Code Cleanup**:
   - Removed two redundant `if` conditions that always evaluated to true, in member-function `Graph::forInEdgesOfImpl`.

## Impact
- These changes are **non-functional** and do not affect the behavior or output of the code.

## Notes
- Changes are limited to the graph module.

As this is my first contribution to NetworkIt, I would greatly appreciate any feedback or suggestions. I am currently familiarizing myself with the codebase and processes, and I aim to contribute additional features in the future. Thank you for your time, guidance, and support as I get started!

2025-01-15 10:53 UTC, fabratu requested changes
Thanks for your contribution!

2025-01-15 10:53 UTC, fabratu commented on networkit/cpp/graph/Graph.cpp
> +        balancedParallelForNodes([&](node uu) {
Good catch! The idiomatic way in NetworKit is to increment the char - better use `w` instead of `uu` here.

2025-01-15 10:53 UTC, fabratu commented on networkit/cpp/graph/Graph.cpp
> +            balancedParallelForNodes([&](node uu) {
Same here.

2025-01-15 17:04 UTC, fabratu approved these changes

2025-01-15 20:53 UTC, angriman requested changes
Usually, we don't use `const` qualifiers for primitive types in function parameters. For example, `node u` should not be `const`:
```cpp
NeighborRange(const Graph &G, const node u) 
```

Since in most cases in NetworKit primitive types in function parameters are not `const`, I'd suggest not doing this change (unless the maintainers agreed to do a full migration).

I agree with the rest of the changes, thank you!

2025-01-16 16:28 UTC, Schwarf commented
Hi @angriman 
I understand your concern. From your comment I take it that I shall all `const` changes all in member()

> Usually, we don't use `const` qualifiers for primitive types in function parameters. For example, `node u` should not be `const`:
> 
> ```c++
> NeighborRange(const Graph &G, const node u) 
> ```
> 
> Since in most cases in NetworKit primitive types in function parameters are not `const`, I'd suggest not doing this change (unless the maintainers agreed to do a full migration).
> 
> I agree with the rest of the changes, thank you!

Hi @angriman,
Thank you for pointing this out! I understand your concern about maintaining consistency with the existing codebase. To align with NetworKit's style, I can revert the `const` qualifiers for primitive types in function parameters. If this aligns with the maintainers' preference, I’ll update the changes accordingly.

If there's ever a discussion or decision to migrate to using const more broadly, I'd be happy to contribute. For now, I’ll focus on adhering to the current conventions.

2025-01-16 17:40 UTC, angriman commented
Yes, I'd suggest reverting `const` changes.

2025-01-16 18:44 UTC, angriman approved these changes
Found some other `const`s, please remove them before merging, thanks!

2025-01-16 18:44 UTC, angriman commented on networkit/cpp/graph/Graph.cpp
> +        balancedParallelForNodes([&](const node w) {
Remove `const`.

2025-01-16 18:44 UTC, angriman commented on networkit/cpp/graph/Graph.cpp
> +            balancedParallelForNodes([&](const node w) {
Ditto.

2025-01-16 18:44 UTC, angriman commented on networkit/cpp/graph/GraphTools.cpp
> +        for (const node u : nodes) {
Ditto.

2025-01-16 18:44 UTC, angriman commented on networkit/cpp/graph/TopologicalSort.cpp
> +    G.forNodes([&](const node u) {
Ditto.

2025-01-19 10:54 UTC, angriman approved these changes

2025-01-28 08:29 UTC, fabratu approved these changes

2025-01-28 08:39 UTC, merged