Profiling: remove broken features
networkit/networkit pull request #617
Opened 2020-10-28 15:30 UTC by angriman

The profiling module was broken some time ago (see #241). This PR removes (temporarily) the features that cause the crashes so that this module can be used again.
Further, it corrects the default value for the `alpha` parameter in the `KatzCentrality` python interface (which did not match the one used in the C++ implementation).

2020-11-25 13:49 UTC, fabratu submitted a review, later dismissed

2020-11-25 13:58 UTC, avdgrinten requested changes
The Katz change is not guaranteed to work. Pick 1/(deg_max+1) instead to guarantee that the Katz centrality is well-defined. This should also be documented.

2020-11-28 09:58 UTC, angriman commented
Isn't that what I am already doing here?

https://github.com/angriman/networkit/blob/1de033991bfe3a9f6fed50e2b85c2953603a40e1/networkit/profiling/profiling.py#L273

2020-11-28 10:30 UTC, avdgrinten commented
Ah, yes. But I am referring to the `__cinit__` (the C++ code should probably be changed, too).

2020-11-28 12:22 UTC, angriman commented
Ah I see. So should we check in the constructor that alpha is `<= 1 / (max_deg + 1)`? Or should we always set alpha to `1 / (max_deg + 1)`?

2020-11-28 12:33 UTC, avdgrinten commented
I guess we should set the default value to 0 or some other special value and let the constructor compute it as 1/(deg_max + 1) if the user does not override the default.

2020-11-29 16:14 UTC, angriman commented
Alright now the code uses by default `1 / (max_deg + 1)` unless the user specifies another positive value.

2020-11-30 11:21 UTC, avdgrinten approved these changes
LGTM.

2020-12-07 08:20 UTC, angriman commented
Some `GTests` with Katz centrality failed because they used the previous default value for alpha, now they are fixed.

2020-12-17 12:46 UTC, avdgrinten submitted a review, later dismissed
Still LGTM.

2020-12-17 12:47 UTC, avdgrinten commented
This PR has conflicts. They need to be resolved before it is merged.

2020-12-17 12:56 UTC, angriman commented
Thanks for the feedback, I rebased the PR.

2020-12-18 11:41 UTC, avdgrinten approved these changes
LGTM.

2020-12-18 11:41 UTC, merged