Restoring the documentation of GraphTools::subgraphFromNodes.
networkit/networkit pull request #726
Opened 2021-03-22 11:40 UTC by Relux-the-Relux

Addressing the unclarity in the function bought up in #651 . By bringing the documentation more in line with what was originally in #374 .

2021-03-22 11:55 UTC, Relux-the-Relux commented
Also should we maybe have a function subgraphFromNodesAndNeighbours for what michitux had expectedd?

2021-03-22 12:12 UTC, hmeyerhenke commented
I would expect this method to return the induced subgraph of the nodes specified as sequence in the parameter list.

2021-03-22 15:36 UTC, michitux commented
@Relux-the-Relux I have no use case for such a method. If this is necessary, I think the user should simply include the neighbors in the set of nodes.

2021-06-03 10:44 UTC, Relux-the-Relux commented
@manpen do you still need the neighbor functionality of this function? we're planning to move it to its own separate function.

2021-06-03 10:51 UTC, Relux-the-Relux commented
@manpen do you still need the neighbor functionality? we're going to move it to its own function.

2021-06-09 15:56 UTC, manpen commented
Dear @Relux-the-Relux, sorry for my delayed response --- I'm currently without a computer of my own and hence cannot look into the details; if I recall correctly, the functionality was used by internal code that was never merged. Thus, feel free to change it (if it does not break NetworKit internals). If necessary I can always fix my code later on.

2021-06-10 09:29 UTC, fabratu requested changes
- No need to re-implement the function, just call `subgraphFromNodesAndEdgesToTheirNeighbors` with everything set to false.
- Also the name of is not optimal. It may imply, that the input-set should already contain the neighbors. Maybe also not ideal, but how about `subgraphAndNeighborsFromNodes`?
- Add a second implementation of `subgraphFromNodes` with all parameters but without default values and deprecate it. The same should be done for Python.

2021-06-10 14:34 UTC, michitux commented
@Relux-the-Relux Sorry for breaking the formatting and there seems to be an include for `<array>` missing. Further, clang seems to be unhappy with my array-loops, probably one should just initialize the array as a proper variable. Do you want to fix that or shall I provide a fix? I don't mind fixing it, I just want to avoid that we both work on the same things.

2021-06-11 08:58 UTC, Relux-the-Relux commented
@michitux If you could apply the fix that'd be great

2021-06-11 13:15 UTC, michitux commented
I have (hopefully) fixed the issues, rebased on current master, renamed the new method as suggested and added a new, deprecated compatibility wrapper. Note that in Python overloading is not possible, therefore there is just a single method with the old parameters first and the new `compact` parameter last. This is a bit unfortunate, but named parameters make it easily possible to just use the new compact parameter.

2021-06-24 09:29 UTC, fabratu approved these changes
LGTM now.

2021-06-29 13:22 UTC, merged