Documentation: Fix missing and non-visible doc-strings for Python modules algebraic, base, centrality
networkit/networkit pull request #866
Opened 2022-01-14 15:58 UTC by fabratu

This PR uses findings from #855 and #865 to fix other Python modules (algebraic, base, centrality). Besides fixing non-visible doc-strings for Python-code, C++ doc-strings for these modules are also added.

2022-01-14 16:14 UTC, angriman requested changes

2022-01-14 16:14 UTC, angriman commented on include/networkit/centrality/PermanenceCentrality.hpp
> + * The permanence centrality measure how well a vertex belongs to its community.
```suggestion
 * Permanence centrality measures how well a vertex belongs to its community.
```

2022-01-14 16:14 UTC, angriman commented on include/networkit/centrality/PermanenceCentrality.hpp
> +     * Constructs the PermanenceCentrality class for the given Graph @a G and Partiion @a P.
```suggestion
     * Constructs the PermanenceCentrality class for the given Graph @a G and Partition @a P. 
```

2022-01-14 16:14 UTC, angriman commented on include/networkit/centrality/PermanenceCentrality.hpp
> +     * @param G The graph.
```suggestion
     * @param G The input graph.
```

2022-01-14 16:14 UTC, angriman commented on include/networkit/centrality/PermanenceCentrality.hpp
> +     * Returns permanence centrality for node @a u.
```suggestion
     * Returns the permanence centrality of node @a u.
```

2022-01-14 16:14 UTC, angriman commented on include/networkit/centrality/PermanenceCentrality.hpp
> +     * @param u Node in the graph.
```suggestion
     * @param u Node in the input graph.
```

2022-01-14 16:14 UTC, angriman commented on include/networkit/centrality/PermanenceCentrality.hpp
> +     * Returns intra clustering for node @a u.
```suggestion
     * Returns the intra-clustering coefficient of node @a u. 
```

2022-01-14 16:14 UTC, angriman commented on include/networkit/centrality/PermanenceCentrality.hpp
> +     * @param u Node in the graph.
```suggestion
     * @param u Node in the input graph.
```

2022-01-14 16:14 UTC, angriman commented on networkit/algebraic.py
> +		represent "sparse" or "dense"
```suggestion
		either "sparse" or "dense"
```

2022-01-14 16:14 UTC, angriman commented on networkit/algebraic.py
> +	Compute a certain eigenvector and -value of the Adjacency matrix of G.
Is `-value` a typo?

2022-01-14 16:14 UTC, angriman commented on networkit/base.pyx
>  			String representation of algorithm and parameters.
This generates conflicts with #864. Since `toString` and `isParallel` (see below) will be removed soon, we can avoid these changes.

2022-01-17 09:14 UTC, avdgrinten commented
I merged the deprecation PR, so this can be fixed now.

2022-01-17 21:00 UTC, angriman approved these changes

2022-01-25 08:34 UTC, merged