Return by const ref when possible
networkit/networkit pull request #896
Opened 2022-02-28 14:25 UTC by angriman

Return by const ref instead of by value when possible.

2022-03-01 08:38 UTC, avdgrinten commented
All these functions return const refs to member variables, right?

2022-03-01 08:39 UTC, angriman commented
Yes

2022-03-01 08:58 UTC, fabratu commented
The Cython interface should also be changed to reflect the new return type, right? Maybe this has also implications for `cdef` definitions.

2022-03-01 09:55 UTC, angriman commented
I am not sure about that, in other places we return by copy as well (e.g. `scores()` in `Centrality`). Don't we need to convert the C++ vector to a Python list anyway?

2022-03-05 13:05 UTC, angriman commented
Returning by reference in Cython seems to work, so I changed it accordingly. Topological sort is the only exception; the C++ implementation has its own class in the `graph` module but, in Python, we implement it as a _static_ function within `graphtools`. Since it is a static function, we cannot return the result by reference. Why do we have this inconsistency?

2022-03-09 14:40 UTC, avdgrinten commented
What happens on the Cython side if we return a const ref? Does Python still do a copy when converting to a list? If not, this would lead to a lifetime issue, wouldn't it?

2022-03-11 23:29 UTC, angriman commented
I think that Python copies when converting to a list. When printing the addresses of the C++ vector and of the Python list we get two different addresses:
```
...
>>> d = apsp.getDistances()
Address: 0x7f55380029f8 <- This is the address of the C++ distance vector
>>> hex(id(d))
'0x7f5585ec2440'
```

2022-03-17 08:58 UTC, fabratu commented
> Returning by reference in Cython seems to work, so I changed it accordingly. Topological sort is the only exception; the C++ implementation has its own class in the `graph` module but, in Python, we implement it as a _static_ function within `graphtools`. Since it is a static function, we cannot return the result by reference. Why do we have this inconsistency?

Hm, good question Maybe it is a better idea to put this in `graph.pyx` as the other graph-classes. If you see fit, than you could add this to the PR. Otherwise I would suggest handle the inconsistency in another PR.

2022-03-17 09:04 UTC, angriman commented
I would recommend fixing `TopologicalSort` in a separate PR.

2022-03-28 13:20 UTC, fabratu requested changes
I think `PLM` and `PLP` both have a inspector `getTiming`-method with internal member variable, which could also benefit from const ref treatment.

2022-03-28 13:20 UTC, fabratu commented on networkit/distance.pyx
> +		vector[edgeweight] &getDistances() except +
While at it, it would be a good idea to also change `SPSP`.

2022-04-05 10:04 UTC, merged