Use std::sample
networkit/networkit pull request #935
Opened 2022-05-05 11:27 UTC by angriman

Use the `std::sample` algorithm introduced in C++17 to sample random nodes.

2022-05-06 08:02 UTC, fabratu approved these changes
LGTM. Do we have any implications concerning the performance of std::sample?

2022-05-06 08:09 UTC, angriman commented
I did not benchmark it. For these general-purpose algorithms, however, the implementation provided by the STL is in general better (more efficient/reliable) than a custom implementation.

2022-05-06 08:38 UTC, fabratu commented
Would suggest the same, thats why I approved it. Just curiosity on whether there are more data points. A quick benchmarking with generated graphs showed for me very similar performance.

2022-05-06 14:21 UTC, hmeyerhenke commented
Please make sure that such changes do not degrade the performance significantly. Some benchmarking should be in place in general. For small/local changes they don't have to be comprehensive. Trust alone can be problematic, though.

2022-05-08 16:22 UTC, avdgrinten requested changes
There should definitely be benchmarks for this PR. *Most* STL implementations are good but there are lots of infamous counter examples. Plus, the existing code already goes into some effort to optimize this function.

2022-06-19 09:58 UTC, angriman commented
It seems that `GraphTools::randomNodes` is indeed faster than `std::sample`, here is a speedup plot: [speed.pdf](https://github.com/networkit/networkit/files/8935095/speed.pdf). I considered graphs with up to 100M nodes from which we sample 10% to 90% of their nodes. Running times for this experiment are between 1e-5 (for the smallest graphs) and 14 seconds (for the largest graphs).

2022-06-21 11:21 UTC, closed without merging