Allow single % and integer weightswith MatrixMarketReader
networkit/networkit pull request #997
Opened 2022-10-04 11:25 UTC by Relux-the-Relux

First, the Matrix Market Format allows for both either a single or double `%` in the first line(https://networkrepository.com/mtx-matrix-market-format.html) so I fixed it in our reader.

Also currently we don't accept integer weights but integer weights and doubles would only not be able to match up for numbers larger than 2^52. Since most weights are smaller than that I think it is better if we accept the weights and just display a warning that for weights larger than 4.5*10^15 the stored weights will not match the given weights perfectly as otherwise, we're just causing an annoyance of having to go back and edit the files to say "real" instead of `integer`.

Lastly, I added tests for the MatrixmMarketRead as there were none.

2022-10-07 09:14 UTC, fabratu requested changes

2022-10-07 09:14 UTC, fabratu commented on networkit/cpp/io/MatrixMarketReader.cpp
> +                This means that weights bigger than 4.5e15 the weights will be recorded imprecisely.");
This means that weights bigger than 4.5*e^15 will be recorded imprecisely.

2022-10-07 09:14 UTC, fabratu commented on networkit/cpp/io/test/IOGTest.cpp
> +TEST_F(IOGTest, testMatrixMarketReader) {
Better have seperate tests for all cases (faster to track down if there are errors).

2022-10-13 07:17 UTC, fabratu requested changes
Please also update the readme for inputfiles -> `https://github.com/networkit/networkit/blob/master/input/README.md`.

2022-10-13 15:47 UTC, angriman commented on networkit/cpp/io/test/IOGTest.cpp
> +    CSRGeneralMatrix csr = reader.read("input/chesapeake.mtx");
If the elements in this matrix are `double`s you can simply use `CSRMatrix`

2022-10-19 11:44 UTC, angriman commented on networkit/cpp/io/test/IOGTest.cpp
> +    CSRMatrix csr = reader.read("input/chesapeake.mtx");
```suggestion
    MatrixMarketReader reader;

    CSRMatrix csr = MatrixMarketReader{}.read("input/chesapeake.mtx");
```
Also in other tests below.

2022-10-19 11:44 UTC, angriman commented on networkit/cpp/io/test/IOGTest.cpp
> +              30 * 2 - 14); // double due to being undirected but we don't double count self loops
```suggestion
    // double due to being undirected but we don't double count self loops
    EXPECT_EQ(csr.nnz(), 30 * 2 - 14);
```

2022-10-27 22:01 UTC, angriman commented on networkit/cpp/io/MatrixMarketReader.cpp
> +static const std::string MAGIC = "%matrixmarket";
```suggestion
static constexpr std::string MAGIC = "%matrixmarket";
```

2022-10-27 22:06 UTC, angriman commented on networkit/cpp/io/MatrixMarketReader.cpp
> +            if (magic != MAGIC && magic != ("%" + MAGIC)) {
```suggestion
            if (magic != MAGIC1 && magic != MAGIC2)) {
```

2022-11-04 11:32 UTC, fabratu commented on networkit/cpp/io/MatrixMarketReader.cpp
> +                This means that weights bigger than 4.5e15 the weights will be recorded imprecisely.");
```suggestion
                This means that weights bigger than 4.5e15 will be recorded imprecisely.");
```

2022-11-17 08:47 UTC, merged